language: minimal
dist: focal
before_install:
  - sudo apt-get -y install gcc-arm-none-eabi libnewlib-arm-none-eabi
  - sudo apt-get -y install flatpak
  - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak install -y --user flathub com.st.STM32CubeIDE
script:
# This flatpak STM32CubeIDE command fails to produce a build, but it generates
# the uncommitted makefile that we need to build manually below.
# So we use it, but suppress errors.
  - flatpak run --command="/app/stm32cubeide/stm32cubeide" com.st.STM32CubeIDE --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data . -importAll . -build all -no-indexer > /dev/null
  - cd dfm17/Release
  - make all
