language: c
dist: jammy
before_install:
  - sudo apt-get -y install flatpak
  - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak install -y --user flathub com.st.STM32CubeIDE
  - flatpak run --command find com.st.STM32CubeIDE || true
  - flatpak run --command /opt/st/headless.sh com.st.STM32CubeIDE
  - false

