language: minimal
dist: jammy
before_install:
  - sudo apt-get -y install flatpak
  - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak install -y --user flathub com.st.STM32CubeIDE
# output is in job 12:  - find `flatpak info -l com.st.STM32CubeIDE `
script:
  - flatpak run --command="/app/stm32cubeide/stm32cubeide" com.st.STM32CubeIDE --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data . -importAll . -build all -no-indexer

